<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>disable</ImplicitUsings>
    <PackageId>Mvp24Hours.Infrastructure.CronJob</PackageId>
    <Authors>Kallebe Lins</Authors>
    <Description>Scheduled background tasks using CRON expressions with OpenTelemetry tracing support.</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://kallebelins.github.io/mvp24hours-dotnet</PackageProjectUrl>
    <Company>Kallebe Lins</Company>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PackageTags>cron;scheduled-jobs;background-service;hosted-service;resilience;opentelemetry;mvp24hours</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Version>10.8.0</Version>
    <AssemblyVersion>10.8.0.1</AssemblyVersion>
    <FileVersion>10.8.0.1</FileVersion>
    <RepositoryUrl>https://github.com/kallebelins/mvp24hours-dotnet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\docs\_media\icon.png" Pack="true" PackagePath="\" Link="icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mvp24Hours.Core\Mvp24Hours.Core.csproj" />
    <ProjectReference Include="..\Mvp24Hours.Infrastructure\Mvp24Hours.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <SonarQubeSetting Include="sonar.stylecop.projectFilePath">
      <Value>$(MSBuildProjectFullPath)</Value>
    </SonarQubeSetting>
  </ItemGroup>

</Project>
