<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NeutralLanguage>en</NeutralLanguage>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <PackageReference Include="Mvp24Hours.Infrastructure.CronJob" Condition="'$(Mvp24HoursUseProjectReferences)' != 'true'" />
    <ProjectReference Include="$(Mvp24HoursSourceRoot)\Mvp24Hours.Infrastructure.CronJob\Mvp24Hours.Infrastructure.CronJob.csproj" Condition="'$(Mvp24HoursUseProjectReferences)' == 'true'" />
  </ItemGroup>
</Project>
