//=====================================================================================
// Developed by Kallebe Lins (https://github.com/kallebelins)
//=====================================================================================
// Reproduction or sharing is free! Contribute to a better world!
//=====================================================================================
namespace Mvp24Hours.Core.Events
{
    /// <summary>
    /// Represents the method that will handle an event when the event provides data.
    /// This delegate is compatible with interfaces (unlike System.EventHandler which requires class constraint).
    /// </summary>
    /// <typeparam name="TSender">The type of sender object (can be interface or class).</typeparam>
    /// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
    /// <param name="sender">The source of the event.</param>
    /// <param name="e">An object that contains the event data.</param>
    public delegate void EventHandler<in TSender, in TEventArgs>(TSender sender, TEventArgs e)
        where TEventArgs : System.EventArgs;
}
