<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mvp24Hours.Infrastructure.Cqrs" Condition="'$(Mvp24HoursUseProjectReferences)' != 'true'" />
    <ProjectReference Include="$(Mvp24HoursSourceRoot)\Mvp24Hours.Infrastructure.Cqrs\Mvp24Hours.Infrastructure.Cqrs.csproj" Condition="'$(Mvp24HoursUseProjectReferences)' == 'true'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerAPI.Domain\CustomerAPI.Domain.csproj" />
  </ItemGroup>

</Project>
