<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<InvariantGlobalization>false</InvariantGlobalization>
		<NeutralLanguage>en</NeutralLanguage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.MongoDb" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
		<PackageReference Include="MongoDB.Driver" />
		<PackageReference Include="Mvp24Hours.WebAPI" Condition="'$(Mvp24HoursUseProjectReferences)' != 'true'" />
		<ProjectReference Include="$(Mvp24HoursSourceRoot)\Mvp24Hours.WebAPI\Mvp24Hours.WebAPI.csproj" Condition="'$(Mvp24HoursUseProjectReferences)' == 'true'" />
		<PackageReference Include="Mvp24Hours.Infrastructure.Data.MongoDb" Condition="'$(Mvp24HoursUseProjectReferences)' != 'true'" />
		<ProjectReference Include="$(Mvp24HoursSourceRoot)\Mvp24Hours.Infrastructure.Data.MongoDb\Mvp24Hours.Infrastructure.Data.MongoDb.csproj" Condition="'$(Mvp24HoursUseProjectReferences)' == 'true'" />
		<PackageReference Include="NLog" />
		<PackageReference Include="NLog.Web.AspNetCore" />
	</ItemGroup>

</Project>
