<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageId>Mvp24Hours.Application</PackageId>
		<Authors>Kallebe Lins</Authors>
		<Description>Application services, CRUD, validation, mapping, specifications, events, transactions, and query caching for Mvp24Hours.</Description>
		<Copyright></Copyright>
		<PackageProjectUrl>https://kallebelins.github.io/mvp24hours-dotnet</PackageProjectUrl>
		<Company>Kallebe Lins</Company>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
		<PackageTags>application;crud;validation;automapper;specification;events;outbox;clean-architecture;mvp24hours</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Version>10.8.0</Version>
		<AssemblyVersion>10.8.0.1</AssemblyVersion>
		<FileVersion>10.8.0.1</FileVersion>
		<RepositoryUrl>https://github.com/kallebelins/mvp24hours-dotnet</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
	</PropertyGroup>

	<ItemGroup>
		<None Update="README.md" Pack="true" PackagePath="\" />
		<None Include="..\..\docs\_media\icon.png" Pack="true" PackagePath="\" Link="icon.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Mvp24Hours.Core\Mvp24Hours.Core.csproj" />
		<ProjectReference Include="..\Mvp24Hours.Infrastructure\Mvp24Hours.Infrastructure.csproj" />
		<ProjectReference Include="..\Mvp24Hours.Infrastructure.Data.EFCore\Mvp24Hours.Infrastructure.Data.EFCore.csproj" />
	</ItemGroup>

	<ItemGroup>
		<SonarQubeSetting Include="sonar.stylecop.projectFilePath">
			<Value>$(MSBuildProjectFullPath)</Value>
		</SonarQubeSetting>
	</ItemGroup>

</Project>
